name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          playwright install --with-deps chromium

      - name: Lint and format
        run: |
          ruff check .
          black --check .

      - name: Run tests
        env:
          SKIP_PLAYWRIGHT_SMOKE: "1"
        run: |
          pytest
